openapi: 3.1.0
info:
  title: Circles Transactions Payment API
  version: 0.0.0
components:
  schemas:
    GeneralError:
      type: object
      properties:
        statusCode:
          type: integer
        code:
          type: string
        error:
          type: string
        message:
          type: string
  responses:
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
paths:
  /transactions:
    post:
      description: Fund the target transaction.
      requestBody: 
        description: '[Gelato sponsoredCall Request Body](https://docs.gelato.network/developer-services/relay/non-erc-2771/sponsoredcall#request-body).'
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Gelato task id.
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: string
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
  /safes:
    post:
      description: Fund the deployment of a new safe and returns the address.
      requestBody: 
        description: '[SafeFactory.deploySafe method parameters](https://github.com/safe-global/safe-core-sdk/tree/main/packages/protocol-kit#deploysafe).'
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: New deployed safe address.
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
